baseURL = "https://content.iriss.org.uk/writing-analysis-social-care"
languageCode = "en-gb"
title = "Writing analysis in social care"
theme = ["hugo-notice", "iriss-course"]
verbose = true
copyrighthtml = "Copyright &#xA9; 2017 John Doe. All Rights Reserved."
menu = "main"
googleAnalytics = "UA-814723-1"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "404"]
publishDir = "docs"
enableInlineShortcodes = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[social]
  twitter = "irissorg"

[params]
  description = "A practical framework for supporting the writing of analysis in social care records"
  images = ["images/tw-card-00.jpg"]
  IrissCourseAuthors  = "Theresa Lillis and Josie Vallely"
  IrissPublishDate = "March 2021"
  IrissCourseYearReleased = "2021"
  IrissHomeTitle = "Writing analysis in social care"
  IrissDescription = "A practical framework for supporting the writing of analysis in social care records"

[markup.tableOfContents]
  endLevel = 2

[privacy]
   [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
