baseURL = "https://content.iriss.org.uk/wasc"
languageCode = "en-gb"
title = "Writing Analysis in Social Care"
theme = ["hugo-notice", "iriss-course"]
verbose = true
copyrighthtml = "Copyright &#xA9; 2017 John Doe. All Rights Reserved."
menu = "main"
googleAnalytics = "UA-814723-1"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "404"]
publishDir = "docs"
enableInlineShortcodes = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  IrissCourseAuthors  = "Theresa Lillis and Josie Vallely"
  IrissPublishDate = "March 2021"
  IrissCourseYearReleased = "2021"
  IrissHomeTitle = "Writing Analysis in Social Care"
  IrissDescription = "A free online course that provides practical support to writing analysis in relation to social work and social care records"

[markup.tableOfContents]
  endLevel = 2

[privacy]
   [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
